config/routes.rb
Rails.application.routes.draw do
  resources :order_meals
  resources :orders
  resources :situations
  resources :meals
  root 'menu#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :categories
  resources :users
end

app/models/situation.rb
class Situation < ApplicationRecord
    has_many :orders
end

app/controllers/situations_controller.rb
class SituationsController < ApplicationController
  before_action :set_situation, only: [:show, :edit, :update, :destroy]

  # GET /situations
  # GET /situations.json
  def index
    @situations = Situation.all
  end

  # GET /situations/1
  # GET /situations/1.json
  def show
  end

  # GET /situations/new
  def new
    @situation = Situation.new
  end

  # GET /situations/1/edit
  def edit
  end

  # POST /situations
  # POST /situations.json
  def create
    @situation = Situation.new(situation_params)

    respond_to do |format|
      if @situation.save
        format.html { redirect_to @situation, notice: 'Situation was successfully created.' }
        format.json { render :show, status: :created, location: @situation }
      else
        format.html { render :new }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /situations/1
  # PATCH/PUT /situations/1.json
  def update
    respond_to do |format|
      if @situation.update(situation_params)
        format.html { redirect_to @situation, notice: 'Situation was successfully updated.' }
        format.json { render :show, status: :ok, location: @situation }
      else
        format.html { render :edit }
        format.json { render json: @situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /situations/1
  # DELETE /situations/1.json
  def destroy
    @situation.destroy
    respond_to do |format|
      format.html { redirect_to situations_url, notice: 'Situation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_situation
      @situation = Situation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def situation_params
      params.require(:situation).permit(:description)
    end
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/views/situations/_form.html.erb
<%= form_with(model: situation, local: true) do |form| %>
<% if situation.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(situation.errors.count, "error") %>
        prohibited this situation from being saved:</h2>

        <ul>
            <% situation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <div class="row">
        <div class="col-3 offset-1">
            <div class="form-group">
                <%= form.label :description, class: "form-label" %>
                <%= form.text_field :description, class: "form-control" %>
            </div>
        </div>

        <div class="col-2 offset-1">
            <div class="check">
                <%= form.submit 'Prosseguir',class: "btn btn-success"%>
            </div>
        </div>

    </div>
    <% end %>

app/views/situations/edit.html.erb
<div class="row">
    <div class="col-11 offset-1">

        <h1>Editar Situation</h1>
    </div>
    <div class="col-12">

        <%= render 'form', situation: @situation %>

    </div>
    <div class="col-1 offset-1">

        <%= link_to 'Voltar', situations_path,class: "btn btn-info" %>
    </div>
    <div class="col-1  ">

        <%= link_to 'Mostar', @situation,class:"btn btn-secondary" %>
    </div>

</div>

app/views/situations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-sm-8 offset-2">


        <table class="table table-bordered table-hover">
            
                <thead>
                    <tr>
                        <th>Description</th>
                        <th colspan="3">Ações</th>
                    </tr>
                </thead>

                <tbody>
                    <% @situations.each do |situation| %>
                    <tr>
                        <td><%= situation.description %></td>
                        <td><%= link_to 'Show', situation,class: "btn btn-secondary" %></td>
                        <td><%= link_to 'Edit', edit_situation_path(situation),class: "btn btn-warning"  %></td>
                        <td><%= link_to 'Destroy', situation, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"  %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>

            <br>

            <%= link_to 'New Situation', new_situation_path ,class: "btn btn-success"%>

        </div>


    </div>

app/views/situations/new.html.erb
<div class="row">
    <div class="col-11 offset-1">

        <h1>Nova Situação</h1>
    </div>
    <div class="col-12">
<%= render 'form', situation: @situation %>

    </div>
    <div class="col-2 offset-1">

        <%= link_to 'Voltar', situations_path,class: "btn btn-info" %>
    </div>

</div>

app/views/situations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @situation.description %>
</p>

<%= link_to 'Edit', edit_situation_path(@situation) %> |
<%= link_to 'Back', situations_path %>