config/routes.rb
Rails.application.routes.draw do
  resources :order_meals
  resources :orders
  resources :situations
  resources :meals
  root 'menu#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :categories
  resources :users
end

app/models/order_meal.rb
class OrderMeal < ApplicationRecord
  belongs_to :order
  belongs_to :meal


end

app/controllers/order_meals_controller.rb
class OrderMealsController < ApplicationController
  before_action :set_order_meal, only: [:show, :edit, :update, :destroy]
  before_action :set_current_order
  # GET /order_meals
  # GET /order_meals.json
  def index
    @order_meals = OrderMeal.all
  end

  # GET /order_meals/1
  # GET /order_meals/1.json
  def show
  end

  # GET /order_meals/new
  def new
    @order_meal = OrderMeal.new
  end

  # GET /order_meals/1/edit
  def edit
  end

  # POST /order_meals
  # POST /order_meals.json
  def create
    @order_meal = OrderMeal.new(order_meal_params)

    respond_to do |format|
      if @order_meal.save
        format.html { redirect_to @order_meal, notice: 'Order meal was successfully created.' }
        format.json { render :show, status: :created, location: @order_meal }
      else
        format.html { render :new }
        format.json { render json: @order_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_meals/1
  # PATCH/PUT /order_meals/1.json
  def update
    respond_to do |format|
      if @order_meal.update(order_meal_params)
        format.html { redirect_to @order_meal, notice: 'Order meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_meal }
      else
        format.html { render :edit }
        format.json { render json: @order_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_meals/1
  # DELETE /order_meals/1.json
  def destroy
    @order_meal.destroy
    respond_to do |format|
      format.html { redirect_to order_meals_url, notice: 'Order meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_meal
      @order_meal = OrderMeal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_meal_params
      params.require(:order_meal).permit(:quantity, :order_id, :meal_id)
    end
end

app/helpers/order_meals_helper.rb
module OrderMealsHelper
end

app/views/order_meals/_form.html.erb
<%= form_with(model: order_meal, local: true) do |form| %>
<% if order_meal.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(order_meal.errors.count, "error") %> prohibited this order_meal from being saved:</h2>

    <ul>
        <% order_meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>
<div class="row">
    <div class="col-3 offset-1">
        <div class="form-group">
            <%= form.label :quantity, class: "form-label" %>
            <%= form.number_field :quantity, class: "form-control" %>
        </div>
    </div>
    <div class="col-3 ">
        <div class="form-group">
            <%= form.label :order_id, class: "form-label" %>
            <%= form.collection_select(:order_id, Order.all, :id,:id, prompt: true,class:"form-control")%>
        </div>
    </div>
    <div class="col-3 ">
        <div class="form-group">
            <%= form.label :meal_id, class: "form-label" %>
            
            <%= form.collection_select(:meal_id, Meal.all, :id,:name, prompt: true,class:"form-control")%>
        </div>
    </div>
    <div class="col-2 offset-1">
        <div class="check">
            <%= form.submit 'Prosseguir',class: "btn btn-success"%>
        </div>
    </div>
</div>
<% end %>

app/views/order_meals/edit.html.erb
<br>
<br>
<br>
<br>
<div class="row">
    <div class="col-11 offset-1">

        <h1>Editar Order Meal</h1>
    </div>
    <div class="col-12">

        <%= render 'form', order_meal: @order_meal %>



    </div>

    <div class="col-2 offset-1 check">

        <%= link_to 'Voltar', order_meals_path,class: "btn btn-info" %>
    </div>
    <div class="col-2 offset-1 check">

        <%= link_to 'Mostar', @order_meal,class:"btn btn-secondary" %>
    </div>

</div>
<br>
<br>
<br>
<br>

app/views/order_meals/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-sm-8 offset-2">


        <table class="table table-bordered table-hover">

            <thead>
                <tr>
                    <th>Quantity</th>
                    <th>Order</th>
                    <th>Meal</th>
                    <th colspan="3">Ações</th>
                </tr>
            </thead>

            <tbody>
                <% @order_meals.each do |order_meal| %>
                <tr>
                    <td><%= order_meal.quantity %></td>
                    <td><%= order_meal.order.id %></td>
                    <td><%= order_meal.meal.name %></td>
                    <td><%= link_to 'Show', order_meal,class: "btn btn-secondary" %></td>
                    <td><%= link_to 'Edit', edit_order_meal_path(order_meal),class: "btn btn-warning" %></td>
                    <td><%= link_to 'Destroy', order_meal, method: :delete, data: { confirm: 'Nani?' }, class:"btn btn-danger" %></td>
                </tr>
                <% end %>
            </tbody>
        </table>

        <br>

        <%= link_to 'New Order Meal', new_order_meal_path ,class: "btn btn-success"%>

    </div>


</div>
<br><br>
<br><br>
<br>
<br>

app/views/order_meals/new.html.erb
<br>
<br>
<br>
<br><div class="row">
    <div class="col-11 offset-1">

        <h1>Nova Order Meal</h1>
    </div>
    <div class="col-12">

        <%= render 'form', order_meal: @order_meal %>


    </div>

    <div class="col-2 offset-1 check">

        <%= link_to 'Voltar', order_meals_path,class: "btn btn-info" %>
    </div>

</div>
<br>
<br>
<br>
<br>

app/views/order_meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @order_meal.quantity %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_meal.order %>
</p>

<p>
  <strong>Meal:</strong>
  <%= @order_meal.meal %>
</p>

<%= link_to 'Edit', edit_order_meal_path(@order_meal) %> |
<%= link_to 'Back', order_meals_path %>