config/routes.rb
Rails.application.routes.draw do
  resources :order_meals
  resources :orders
  resources :situations
  resources :meals
  root 'menu#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  resources :categories
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  enum admin: [:normal_user, :admin_user]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
   before_action :configure_sign_up_params, only: [:create]
   before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
   end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
   def edit
     super
   end

  # PUT /resource
   def update
     super
   end

  # DELETE /resource
   def destroy
     super
   end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

    protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :admin])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    protect_from_forgery with: :exception
    before_action :authenticate_user!

    before_action :authenticate_admin
    def user_params
        params.require(:user).permit(:name,:admin,:email)
    end

    def index
        @users = User.all
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to users_path, :notice => "Usuário editado."
        else
            redirect_to users_path, :alert => "Usuário já existente ou em branco."
        end
    end
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to users_path, :notice => "Usuário Criado."
        else
            redirect_to users_path, :alert => "Usuário já existente ou em branco."
        end
    end

    def destroy
        @user = User.find(params[:id])
        if @user.delete
            redirect_to users_path
        end
    end
end

app/views/users/_back-office.html.erb
<div class="navbar navbar-expand-lg navbar-dark bg-dark">
  <% if current_page?(orders_path) %>
    <%= link_to "Pedidos", orders_path, class: "nav-link active padding-left mr-auto font-white" %>
  <% else %>
    <%= link_to "Pedidos", orders_path, class: "nav-link active padding-left mr-auto font-white" %>
  <% end %>

  <% if current_page?(users_path)%>
    <%= link_to "Usuários", users_path, class: "nav-link active mr-auto font-white" %>
  <% else %>
    <%= link_to "Usuários", users_path, class: "nav-link padding-left mr-auto font-white" %>
  <% end %>

  <% if current_page?(meals_path) %>
    <%= link_to "Refeições", meals_path, class: "nav-link active mr-auto font-white" %>
  <% else %>
    <%= link_to "Refeições", meals_path, class: "nav-link active mr-auto font-white" %>
  <% end %>

  <% if current_page?(categories_path) %>
    <%= link_to "Categorias de Refeição", categories_path, class: "nav-link active mr-auto font-white" %>
  <% else %>
    <%= link_to "Categorias de Refeição", categories_path, class: "nav-link mr-auto font-white" %>
  <% end %>
  <% if current_page?(categories_path) %>
    <%= link_to "Order Meal", order_meals_path, class: "nav-link active mr-auto font-white" %>
  <% else %>
    <%= link_to "Order Meal", order_meals_path, class: "nav-link mr-auto font-white" %>
  <% end %>
</div>

app/views/users/_footer.html.erb
<footer class="">
  <div class="row">
      <div class="col-3 offset-1 direitos">
          <h6>DinnerDash | Todos os direitos reservados</h6>
      </div>
      <div class="offset-5 col-3 desenvolvido">
          <h6>Desenvolvido por GO&VB</h6>
      </div>
  </div>
</footer>

app/views/users/_user-options.html.erb
<% if current_user == nil %>
    <div class="index-image">
        <div class="image-text">
            <div class="navbar navbar-extand-lg">
                <h1 class="nav-link dinnerdash-nav padding-left">Dinnerdash</h1>
                <div class="navbar-nav ml-auto"><%= link_to "cadastro", new_user_registration_path, :class => 'nav-link font-white'  %></div>
                <%= link_to "entrar", new_user_session_path, :class => 'nav-link font-white'  %>
                
            </div>
            <div class="text-bottom">
                
                <h1 class="title monte-prato padding-top padding-left">Monte o seu prato</h1>
                <h3 class="subtitle escolha padding-left">Escolha sua salada, molho, guarnição, prato principal e bebida.</h3>
            </div>
        </div>
    </div>
<% else %>
    <% if current_user.normal_user? %>
        <% if current_page?(edit_user_registration_path) %>
            <div class="perfil-image">
                <div class="image-text">
                    <div class="navbar navbar-extand-lg">
                        <h1 class="nav-link dinnerdash-nav padding-left">Dinnerdash</h1>
                        <div class="navbar-nav ml-auto"><%= link_to 'perfil', edit_user_registration_path, :class => 'nav-link font-white' %></div>
                        <%= link_to "sair", destroy_user_session_path, method: :delete, :class => 'nav-link font-white'  %>
                    </div>
                    <h1 class="title monte-prato padding-top padding-left"><strong>Seu Perfil</strong> </h1>
                    <h3 class="subtitle escolha padding-left">Atualize seus dados pessoais e senha.</h3>
                </div>
            </div>
        <% else %>
            <div class="index-image">
                <div class="image-text">
                    <div class="navbar navbar-extand-lg">
                        <h1 class="nav-link dinnerdash-nav padding-left">Dinnerdash</h1>
                        <div class="navbar-nav ml-auto"><%= link_to 'perfil', edit_user_registration_path, :class => 'nav-link font-white' %></div>
                        <%= link_to "sair", destroy_user_session_path, method: :delete, :class => 'nav-link font-white'  %>
                    </div>
                    <h1 class="title monte-prato padding-top padding-left"><strong> Bem-vindo, <%=current_user.name%></strong> </h1>
                    <h3 class="subtitle escolha padding-left">Escolha sua salada, molho, guarnição, prato principal e bebida.</h3>
                </div>
            </div>
        <% end %>
    <% elsif current_user.admin_user? %>
        <div class="back-office-image">
            <div class="image-text">
                <div class="navbar navbar-extand-lg">
                    <h1 class="nav-link dinnerdash-nav padding-left">Dinnerdash</h1>
                    <h1 class="nav-link dinnerdash-nav padding-left logo-office">backoffice</h1>
                    <div class="navbar-nav ml-auto"><%= link_to 'perfil', edit_user_registration_path, :class => 'nav-link font-white' %></div>
                    <%= link_to "sair", destroy_user_session_path, method: :delete, :class => 'nav-link font-white'  %>
                </div>
                <h1 class="title font-white padding-top padding-left"><strong> Backoffice </strong></h1>
                <h3 class="subtitle font-white padding-left">Gerencie pedidos, refeições e mais.</h3>
            </div>
        </div>
        <div> <%= render 'users/back-office' %> </div>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<br>
<br>
<div class="row">

    <div class="col-10 offset-2">
        <h3>Editar Usuário</h3>
    </div>

    <div class="col-5 offset-2">

        <%= form_for @user do |f| %>


        <p >
            <%= f.label :name, "Nome", class: "form-label" %><br>
            <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </p>

        <p >
            <%= f.label :email, "Email", class: "form-label" %><br>
            <%= f.text_field :email, autofocus: true, class: "form-control" %>
        </p>

        <p>
            <%= f.label :admin, "Perfil", class: "form-label" %>
            <%= f.collection_select(:admin, User.all, :admin, :admin, prompt: true,class:"form-control") %>
        </p>

        <p>

            <%= @user.remember_created_at %>
        </p>
        <br>
        <br>

        <p >
            <%= f.submit "Atualizar Usuário", class: "btn btn-success"%>
            <%= link_to 'Voltar', users_path, class: "btn btn-secondary" %>
        </p>


        <% end %>
    </div>

</div>

app/views/users/index.html.erb
<div class="row">
<div class="col-10 offset-1">

<br>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Password</th>
                <th>Admin</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody >
            <% @users.each do |user| %>
            <tr >
                <td> <%=user.id %> </td>
                <td>  <%=user.name %> </td>
                <td><%= user.email %> </td>
                <td><%= user.encrypted_password %> </td>
                <td><%= user.admin %> </td>
                <td><%= link_to 'Editar', edit_user_path(user.id),   class:"btn btn-warning"%> <%= link_to "Excluir", user_registration_path(user.id), method: :delete, class:"btn btn-danger"%>  </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <%= link_to 'Novo User', new_user_registration_path,class: "btn btn-success"%>

</div>


</div>
<br>